import { create } from 'zustand';

interface FeedItem {
  id: number;
  title: string;
  points?: number | null;
  user?: string | null;
  time: number;
  time_ago: string;
  comments_count: number;
  type: string;
  url?: string;
  domain?: string;
}

interface State {
  feed: FeedItem[];
  visibleFeed: FeedItem[];
  currentPage: number;
}

interface Action {
  updateFeed: (feed: FeedItem[]) => void;
}

const mockFeed: FeedItem[] = [
  {
    id: 40983680,
    title: 'No More Tears, No More Knots: Arena-Allocated Trees in Rust',
    points: 2,
    user: 'g0xA52A2A',
    time: 1721205273,
    time_ago: '5 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://deciduously.com/blog/rust_arena_trees/',
    domain: 'deciduously.com',
  },
  {
    id: 40983674,
    title: 'Boosting PHP performance: mastering OPcache optimization with Blackfire',
    points: 1,
    user: 'tdlx',
    time: 1721205164,
    time_ago: '7 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://blog.blackfire.io/boosting-php-performance-mastering-opcache-optimization-with-blackfire.html',
    domain: 'blog.blackfire.io',
  },
  {
    id: 40983669,
    title: 'Time might be a mirage created by quantum physics, study suggests',
    points: 1,
    user: 'isaacfrond',
    time: 1721205088,
    time_ago: '9 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://www.livescience.com/physics-mathematics/quantum-physics/time-might-be-a-mirage-created-by-quantum-physics-study-suggests',
    domain: 'livescience.com',
  },
  {
    id: 40983658,
    title: 'Disney – Design and Control of a Bipedal Robotic Character',
    points: 1,
    user: 'v9v',
    time: 1721204930,
    time_ago: '11 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://www.youtube.com/watch?v=7_LW7u-nk6Q',
    domain: 'youtube.com',
  },
  {
    id: 40983657,
    title: "FBI cracked Trump shooter's phone with tech from Israel's Cellebrite",
    points: 1,
    user: 'isaacfrond',
    time: 1721204922,
    time_ago: '11 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://www.timesofisrael.com/fbi-cracked-trump-shooters-phone-with-tech-from-israels-cellebrite-report/',
    domain: 'timesofisrael.com',
  },
  {
    id: 40983653,
    title: 'Dispersion-assisted high-dimensional photodetector',
    points: 1,
    user: 'quxinxin',
    time: 1721204871,
    time_ago: '12 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://www.nature.com/articles/s41586-024-07398-w',
    domain: 'nature.com',
  },
  {
    id: 40983604,
    title: 'Aana SDK: open-source library for building multimodal AI applications',
    points: 1,
    user: 'ibuildthings',
    time: 1721204372,
    time_ago: '20 minutes ago',
    comments_count: 1,
    type: 'link',
    url: 'https://mobiusml.github.io/aana-sdk-introducing-blog/',
    domain: 'mobiusml.github.io',
  },
  {
    id: 40983596,
    title: 'Tails 6.5',
    points: 1,
    user: 'h0ek',
    time: 1721204307,
    time_ago: '22 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://tails.net/news/version_6.5/index.en.html',
    domain: 'tails.net',
  },
  {
    id: 40983594,
    title: 'Oracle Releases VirtualBox 7.0.20',
    points: 1,
    user: 'h0ek',
    time: 1721204290,
    time_ago: '22 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://alternativeto.net/news/2024/7/oracle-releases-virtualbox-7-0-20-new-linux-kernel-support-clipboard-fixes-and-more/',
    domain: 'alternativeto.net',
  },
  {
    id: 40983587,
    title: 'Ask HN: Any tools to get an aggregated view of bank accounts for startups?',
    points: 1,
    user: 'virtualitis',
    time: 1721204230,
    time_ago: '23 minutes ago',
    comments_count: 0,
    type: 'ask',
    url: 'item?id=40983587',
  },
  {
    id: 40983585,
    title: 'Google presents method to circumvent automatic blocking of tag manager',
    points: 2,
    user: 'iamacyborg',
    time: 1721204193,
    time_ago: '23 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://developers.google.com/tag-platform/tag-manager/first-party/setup-guide',
    domain: 'developers.google.com',
  },
  {
    id: 40983573,
    title: 'Fats from thin air: Startup makes butter using CO2 and water',
    points: 1,
    user: 'isaacfrond',
    time: 1721204045,
    time_ago: '26 minutes ago',
    comments_count: 1,
    type: 'link',
    url: 'https://newatlas.com/technology/savor-butter-bill-gates/',
    domain: 'newatlas.com',
  },
  {
    id: 40983535,
    title: 'StatsBomb Release Free Euro 2024 Data',
    points: 2,
    user: 'kiyanwang',
    time: 1721203593,
    time_ago: '33 minutes ago',
    comments_count: 1,
    type: 'link',
    url: 'https://statsbomb.com/news/statsbomb-release-free-euro-2024-data/',
    domain: 'statsbomb.com',
  },
  {
    id: 40983518,
    title: 'Multi-Version Schema Migrations',
    points: 1,
    user: 'jacobwg',
    time: 1721203380,
    time_ago: '37 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://xata.io/blog/multi-version-schema-migrations',
    domain: 'xata.io',
  },
  {
    id: 40983500,
    title: 'Libera IRC Channels Sorted by Number of Users',
    points: 2,
    user: 'susam',
    time: 1721203181,
    time_ago: '40 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://netsplit.de/channels/?net=Libera.Chat',
    domain: 'netsplit.de',
  },
  {
    id: 40983497,
    title: 'Exclusive-Google-backed software developer Gitlab explores sale, sources say',
    points: 2,
    user: 'yla92',
    time: 1721203160,
    time_ago: '41 minutes ago',
    comments_count: 1,
    type: 'link',
    url: 'https://www.channelnewsasia.com/business/exclusive-google-backed-software-developer-gitlab-explores-sale-sources-say-4485231',
    domain: 'channelnewsasia.com',
  },
  {
    id: 40983486,
    title: 'Gitlab Explores Sale',
    points: 7,
    user: 'gostsamo',
    time: 1721203046,
    time_ago: '43 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://www.reuters.com/markets/deals/google-backed-software-developer-gitlab-explores-sale-sources-say-2024-07-17/',
    domain: 'reuters.com',
  },
  {
    id: 40983484,
    title: "Design a GraphQL Schema So Good, It'll Make REST APIs Cry",
    points: 3,
    user: 'thunderbong',
    time: 1721203030,
    time_ago: '43 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://tailcall.run/blog/graphql-schema/',
    domain: 'tailcall.run',
  },
  {
    id: 40983421,
    title: "We Love Writing Software So Much, We're Willing to Do It for Free",
    points: 20,
    user: 'ohduran',
    time: 1721202077,
    time_ago: 'an hour ago',
    comments_count: 13,
    type: 'link',
    url: 'https://news.alvaroduran.com/p/we-love-writing-software-so-much',
    domain: 'news.alvaroduran.com',
  },
  {
    id: 40983414,
    title: 'Show HN: Online Media Conversion Tool',
    points: 1,
    user: 'vednig',
    time: 1721201980,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://convertr.xyz/',
    domain: 'convertr.xyz',
  },
  {
    id: 40983412,
    title: 'Relevance Theory',
    points: 1,
    user: 'yamrzou',
    time: 1721201972,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://en.wikipedia.org/wiki/Relevance_theory',
    domain: 'en.wikipedia.org',
  },
  {
    id: 40983407,
    title: 'Not Speeding Up Delta Decoding with Value Speculation',
    points: 1,
    user: 'sakras',
    time: 1721201853,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://save-buffer.github.io/not_speeding_up_delta_decoding.html',
    domain: 'save-buffer.github.io',
  },
  {
    id: 40983392,
    title: 'How Coca-Cola Obtains Its Coca',
    points: 2,
    user: 'thunderbong',
    time: 1721201596,
    time_ago: 'an hour ago',
    comments_count: 2,
    type: 'link',
    url: 'https://www.nytimes.com/1988/07/01/business/how-coca-cola-obtains-its-coca.html',
    domain: 'nytimes.com',
  },
  {
    id: 40983380,
    title: 'Seiko Had a Smartwatch in 1984',
    points: 3,
    user: 'WithinReason',
    time: 1721201360,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://hackaday.com/2024/07/16/seiko-had-a-smartwatch-in-1984/',
    domain: 'hackaday.com',
  },
  {
    id: 40983364,
    title: 'ClearRx',
    points: 1,
    user: 'thunderbong',
    time: 1721201131,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://en.wikipedia.org/wiki/ClearRx',
    domain: 'en.wikipedia.org',
  },
  {
    id: 40983363,
    title: 'Exploring the Vastness of a Website',
    points: 1,
    user: 'cookingoils',
    time: 1721201121,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://sites.elliott.computer/exploring-the-vastness-of-a-website.html',
    domain: 'sites.elliott.computer',
  },
  {
    id: 40983357,
    title: "When whimsical wildlife photography isn't what it seems",
    points: 2,
    user: '11001100',
    time: 1721201037,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://www.pbs.org/newshour/science/whimsical-wildlife-photography-isnt-seems',
    domain: 'pbs.org',
  },
  {
    id: 40983341,
    title: 'Mapping High Level Constructs to LLVM IR',
    points: 2,
    user: 'todsacerdoti',
    time: 1721200817,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/',
    domain: 'mapping-high-level-constructs-to-llvm-ir.readthedocs.io',
  },
  {
    id: 40983329,
    title: 'How to use the new counted_by attribute in C (and Linux)',
    points: 2,
    user: 'sohkamyung',
    time: 1721200645,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://people.kernel.org/gustavoars/how-to-use-the-new-counted_by-attribute-in-c-and-linux',
    domain: 'people.kernel.org',
  },
  {
    id: 40983328,
    title: 'Show HN: Pippy – Pipelines for GitHub Actions',
    points: 3,
    user: 'awenix',
    time: 1721200643,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://pippy.dev/',
    domain: 'pippy.dev',
  },
];

//todo добавить поля visibleFeed
const useFeedStore = create<Action & State>()((set) => ({
  feed: mockFeed,
  visibleFeed: mockFeed,
  currentPage: 1,
  updateFeed: (feed) => set(() => ({ feed: feed }), true),
}));

export default useFeedStore;
